artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1hMsXd5m_7Ph_Hw2ke8E2dp9w1VExvGMQ/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data_zip
  unzip_dir: artifacts/data_ingestion